#!/usr/bin/env python3
"""
build_frames.py — turn the raw 1080p JPEG frame dumps in assets/seq/<name>/
into the two lightweight WebP tiers the site actually plays back.

  source:  assets/seq/hero/ezgif-frame-001.jpg ... (1920x1080, ~67 KB each)
  output:  assets/seq/hero/md/f000.webp ...        (desktop tier)
           assets/seq/hero/sm/f000.webp ...        (phone tier)
           assets/seq/hero/poster.jpg              (static fallback)
           js/seq-manifest.js                      (frame counts per tier)

Frames are decimated as well as downscaled: a scroll-scrubbed sequence does not
need 240 frames, and every frame we drop is one the browser never has to hold.

    python tools/build_frames.py            # build everything
    python tools/build_frames.py hero work  # rebuild just these
"""

import json
import os
import re
import sys
from concurrent.futures import ProcessPoolExecutor

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEQ_DIR = os.path.join(ROOT, "assets", "seq")

# tier -> (max stored frames, target width, webp quality)
TIERS = {
    "md": (80, 1152, 58),
    "sm": (44, 640, 55),
}
POSTER_WIDTH = 1280
POSTER_QUALITY = 72
FRAME_RE = re.compile(r"^ezgif-frame-(\d+)\.jpg$", re.I)


def source_frames(name):
    """Original frames for a sequence, in order."""
    d = os.path.join(SEQ_DIR, name)
    files = [f for f in os.listdir(d) if FRAME_RE.match(f)]
    files.sort(key=lambda f: int(FRAME_RE.match(f).group(1)))
    return [os.path.join(d, f) for f in files]


def pick(srcs, limit):
    """Evenly spread `limit` frames across the source list (always keeps the ends)."""
    n = len(srcs)
    if n <= limit:
        return list(range(n))
    return [round(i * (n - 1) / (limit - 1)) for i in range(limit)]


def encode(args):
    src, dst, width, quality = args
    with Image.open(src) as im:
        im = im.convert("RGB")
        if im.width > width:
            im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
        im.save(dst, "WEBP", quality=quality, method=4)
    return os.path.getsize(dst)


def build(name):
    srcs = source_frames(name)
    if not srcs:
        print(f"  {name}: no source frames, skipped")
        return None

    out_dir = os.path.join(SEQ_DIR, name)
    entry = {"source": len(srcs)}
    jobs = []

    for tier, (limit, width, quality) in TIERS.items():
        tier_dir = os.path.join(out_dir, tier)
        os.makedirs(tier_dir, exist_ok=True)
        for f in os.listdir(tier_dir):  # drop stale frames from an earlier run
            if f.endswith(".webp"):
                os.remove(os.path.join(tier_dir, f))
        idxs = pick(srcs, limit)
        entry[tier] = len(idxs)
        for i, si in enumerate(idxs):
            jobs.append((srcs[si], os.path.join(tier_dir, f"f{i:03d}.webp"), width, quality))

    with ProcessPoolExecutor() as pool:
        total = sum(pool.map(encode, jobs, chunksize=4))

    # poster: a representative still, used for reduced-motion, save-data and no-WebP
    with Image.open(srcs[len(srcs) // 3]) as im:
        im = im.convert("RGB")
        if im.width > POSTER_WIDTH:
            im = im.resize((POSTER_WIDTH, round(im.height * POSTER_WIDTH / im.width)), Image.LANCZOS)
        poster = os.path.join(out_dir, "poster.jpg")
        im.save(poster, "JPEG", quality=POSTER_QUALITY, optimize=True, progressive=True)
    total += os.path.getsize(poster)

    before = sum(os.path.getsize(s) for s in srcs)
    print(
        f"  {name}: {len(srcs)} -> md {entry['md']} / sm {entry['sm']} frames, "
        f"{before / 1048576:.1f} MB -> {total / 1048576:.1f} MB"
    )
    return entry


def main():
    names = sys.argv[1:] or sorted(
        d for d in os.listdir(SEQ_DIR) if os.path.isdir(os.path.join(SEQ_DIR, d))
    )
    manifest_path = os.path.join(ROOT, "js", "seq-manifest.js")
    manifest = {}
    if os.path.exists(manifest_path):  # keep entries for sequences we are not rebuilding
        with open(manifest_path, encoding="utf-8") as fh:
            body = fh.read()
        start, end = body.find("{"), body.rfind("}")
        if start != -1:
            manifest = json.loads(body[start : end + 1])

    print("building frame tiers...")
    for name in names:
        entry = build(name)
        if entry:
            manifest[name] = entry

    with open(manifest_path, "w", encoding="utf-8") as fh:
        fh.write("/* generated by tools/build_frames.py — do not edit by hand */\n")
        fh.write("window.SEQ_MANIFEST = ")
        json.dump(manifest, fh, indent=2, sort_keys=True)
        fh.write(";\n")
    print(f"wrote {os.path.relpath(manifest_path, ROOT)}")


if __name__ == "__main__":
    main()
